sudo: required

dist: xenial

language: go

services:
  - docker

go:
  - 1.14.2

env:
  - GO111MODULE=on DOCKER_CLI_EXPERIMENTAL=enabled

before_install:
  - sudo apt-get update && sudo apt-get -y install jq

install: true

script:
  - make
  - make clean
  - make unit
  - make lint
  - make container

after_success:
  - docker login -u="$DOCKER_USERNAME" -p="$DOCKER_PASSWORD"
  - docker run --rm --privileged multiarch/qemu-user-static --reset -p yes
  - make manifest && make manifest-latest
